// apps/web/tests/serve-config.test.mjs: the shape GET /local/config.json answers with, executed
// from the exact function script/anvil/serve.sh runs, without binding a socket or needing a chain.
//
// serve.sh keeps its server in a heredoc, so the function is sliced out between two marker comments
// and evaluated here. If the markers move or the function is renamed, this file fails loudly rather
// than testing a copy that drifted.

import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, dirname } from "node:path";
import { test } from "node:test";

import {
  LOCAL_MANIFEST,
  LOCAL_MANIFEST_WITHOUT_DIRECT_SETTLER,
  LOCAL_TOKEN_LABELS,
  TAST,
  UUSD,
} from "./fixtures/local-manifest.fixture.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..", "..");
const source = readFileSync(join(ROOT, "script", "anvil", "serve.sh"), "utf8");

const begin = source.indexOf("// @runtimeConfig-begin");
const end = source.indexOf("// @runtimeConfig-end");
assert.ok(begin > 0 && end > begin, "serve.sh carries the @runtimeConfig markers");
const slice = source.slice(begin, end);
const runtimeConfig = new Function(`${slice}\nreturn runtimeConfig;`)();

// THE MANIFEST THESE ROWS OWN. Hand written, committed, and unaffected by whether anyone has run
// the demo on this machine. `deployments/31337.local.json` is gitignored and regenerated by every
// `make business-demo` and `make anvil-test`, so a row that asserted a fixed value out of it was
// asserting against state that legitimately moves; see the fixture's own note.
const fullManifest = LOCAL_MANIFEST;

// The runtime manifest, when this machine happens to have one. Read separately, asserted
// separately, and never required: its absence is a normal state on a fresh clone.
const RUNTIME_MANIFEST_PATH = join(ROOT, "deployments", "31337.local.json");
const runtimeManifest = existsSync(RUNTIME_MANIFEST_PATH)
  ? JSON.parse(readFileSync(RUNTIME_MANIFEST_PATH, "utf8"))
  : null;

test("the served config still carries rpc, chainId, manifest and record", () => {
  const c = runtimeConfig({ chainId: 31337, contracts: {}, identity: {} }, { order: { id: "x" } }, "REDACTED");
  assert.equal(c.rpc, "REDACTED");
  assert.equal(c.chainId, 31337);
  assert.deepEqual(c.record, { order: { id: "x" } });
  assert.equal(c.manifest.chainId, 31337);
});
test("a manifest without an onboarding contract exposes null for every join field, never a guess", () => {
  const c = runtimeConfig({ chainId: 31337, contracts: { identityFixture: { address: "0x1" }, identityToken: { address: "0x2" } }, identity: { terminalStatusKey: "com.unica.terminal-status" } }, null, "REDACTED");
  assert.equal(c.merchantOnboarding, null);
  assert.equal(c.parentNode, null);
  assert.equal(c.parentName, null);
  assert.equal(c.identity, "0x1");
  assert.equal(c.identityToken, "0x2");
  assert.equal(c.terminalStatusKey, "com.unica.terminal-status");
});
test("a manifest with an onboarding contract exposes all five join fields", () => {
  const c = runtimeConfig({
    chainId: 31337,
    contracts: { merchantOnboarding: { address: "0xaaa" }, identityFixture: { address: "0xbbb" }, identityToken: { address: "0xccc" } },
    identity: { parentNode: "0x" + "1".repeat(64), parentName: "unica.eth", terminalStatusKey: "com.unica.terminal-status" }, // parentNode bytes32 vector
  }, null, "REDACTED");
  assert.equal(c.merchantOnboarding, "0xaaa");
  assert.equal(c.identity, "0xbbb");
  assert.equal(c.identityToken, "0xccc");
  assert.equal(c.parentNode, "0x" + "1".repeat(64)); // bytes32 vector
  assert.equal(c.parentName, "unica.eth");
});
test("a full manifest is served without a crash and says what it lacks", () => {
  const c = runtimeConfig(fullManifest, null, "REDACTED");
  assert.equal(c.chainId, 31337);
  assert.equal(c.identity, fullManifest.contracts.identityFixture.address);
  assert.equal(c.identityToken, fullManifest.contracts.identityToken.address);
  // A manifest may or may not carry merchantOnboarding. Either answer is fine; an exception is not.
  assert.ok(c.merchantOnboarding === null || /^0x[0-9a-fA-F]{40}$/.test(c.merchantOnboarding));
});
test("an empty manifest yields nulls, not a crash", () => {
  const c = runtimeConfig(undefined, null, "REDACTED");
  assert.equal(c.chainId, null);
  assert.equal(c.merchantOnboarding, null);
});

// ---- the business screens' half of the configuration ------------------------------------------

// The two local test assets and their read-off-chain labels come from the fixture, so these rows
// and the full-manifest rows below are talking about the same two tokens.
const LABELS = LOCAL_TOKEN_LABELS;
const withAssets = {
  chainId: 31337,
  environment: "LOCAL_ANVIL_NO_VALUE",
  contracts: { payoutToken: { address: UUSD }, assetToken: { address: TAST }, executor: { address: "0xexec" } },
  market: { marketId: "0xmarket", poolKey: { currency0: UUSD, currency1: TAST }, poolId: "0xpool", status: 4 },
  identity: {},
};

test("the assets are served with the role, symbol and decimal count each screen needs", () => {
  const c = runtimeConfig(withAssets, null, "REDACTED", LABELS);
  assert.deepEqual(c.assets.map((a) => [a.role, a.symbol, a.decimals, a.labelled]), [
    ["payout", "uUSD", 6, true],
    ["customer", "tAST", 18, true],
  ]);
  assert.equal(c.assets[0].address, UUSD);
});
test("an asset whose label could not be read is served unlabelled, never guessed", () => {
  const c = runtimeConfig(withAssets, null, "REDACTED", {});
  assert.deepEqual(c.assets.map((a) => [a.symbol, a.decimals, a.labelled]), [
    [null, null, false],
    [null, null, false],
  ]);
});
test("the market pair is active only at status 4", () => {
  assert.equal(runtimeConfig(withAssets, null, "REDACTED", LABELS).marketPair.active, true);
  const paused = { ...withAssets, market: { ...withAssets.market, status: 5 } };
  assert.equal(runtimeConfig(paused, null, "REDACTED", LABELS).marketPair.active, false);
  const seeded = { ...withAssets, market: { ...withAssets.market, status: 3 } };
  assert.equal(runtimeConfig(seeded, null, "REDACTED", LABELS).marketPair.active, false);
});
test("a manifest with no market serves no pair at all, rather than an empty one that looks usable", () => {
  const c = runtimeConfig({ chainId: 31337, contracts: {}, identity: {} }, null, "REDACTED", {});
  assert.equal(c.marketPair, null);
});
test("the direct settler is null until the deployment carries one", () => {
  assert.equal(runtimeConfig(withAssets, null, "REDACTED", LABELS).contracts.directSettlement, null);
  const withDirect = { ...withAssets, contracts: { ...withAssets.contracts, directSettlement: { address: "0xdirect" } } };
  assert.equal(runtimeConfig(withDirect, null, "REDACTED", LABELS).contracts.directSettlement, "0xdirect");
});
test("the environment the manifest declares is served verbatim, for the label rule to judge", () => {
  assert.equal(runtimeConfig(withAssets, null, "REDACTED", LABELS).environment, "LOCAL_ANVIL_NO_VALUE");
  assert.equal(runtimeConfig({ chainId: 1, contracts: {}, identity: {} }, null, "REDACTED", {}).environment, null);
});
test("a full manifest serves both of its assets, its market pair and its direct settler", () => {
  const c = runtimeConfig(fullManifest, null, "REDACTED", LOCAL_TOKEN_LABELS);
  assert.equal(c.assets.length, 2);
  assert.deepEqual(
    c.assets.map((a) => [a.role, a.address, a.symbol]),
    [
      ["payout", UUSD, "uUSD"],
      ["customer", TAST, "tAST"],
    ],
  );
  assert.equal(c.marketPair.marketId, fullManifest.market.marketId);
  assert.equal(c.marketPair.active, true); // the fixture records status 4, ACTIVE
  assert.equal(c.contracts.executor, fullManifest.contracts.executor.address);
  assert.equal(c.contracts.directSettlement, fullManifest.contracts.directSettlement.address);
});
test("the same deployment before the direct settler existed serves null, not a guess", () => {
  const c = runtimeConfig(LOCAL_MANIFEST_WITHOUT_DIRECT_SETTLER, null, "REDACTED", LOCAL_TOKEN_LABELS);
  assert.equal(c.contracts.directSettlement, null);
  // The control on the row above: everything else about the two manifests is identical, so the
  // difference in that one field is the settler and nothing else.
  assert.equal(c.contracts.executor, fullManifest.contracts.executor.address);
  assert.equal(c.marketPair.marketId, fullManifest.market.marketId);
});
test("the runtime manifest on this machine, if there is one, is served verbatim", () => {
  if (!runtimeManifest) {
    // A stated negative, not a silent skip: no local deployment on this machine, nothing to serve.
    console.log("      (no deployments/31337.local.json on this machine — nothing to serve, nothing asserted)");
    return;
  }
  const c = runtimeConfig(runtimeManifest, null, "REDACTED");
  assert.equal(c.chainId, runtimeManifest.chainId);
  assert.equal(c.environment, runtimeManifest.environment ?? null);
  // Whatever the deployment carries is what is served. Asserting a FIXED answer here is what made
  // the earlier version of this row fail the moment the installation started deploying a settler.
  assert.equal(c.contracts.directSettlement, runtimeManifest.contracts?.directSettlement?.address ?? null);
  assert.equal(c.contracts.executor, runtimeManifest.contracts?.executor?.address ?? null);
  assert.equal(c.marketPair?.marketId ?? null, runtimeManifest.market?.marketId ?? null);
});

test("holdings are the two payment assets plus every known token, each listed once, labelled only when read", () => {
  const A = "0x000000000000000000000000000000000000000a";
  const B = "0x000000000000000000000000000000000000000b";
  const K = "0x000000000000000000000000000000000000000c";
  const c = runtimeConfig(
    { contracts: { payoutToken: { address: A }, assetToken: { address: B } }, knownTokens: [{ address: K }, { address: A.toUpperCase().replace("0X", "0x") }] },
    null,
    "http://127.0.0.1:8545",
    { [A]: { symbol: "uUSD", decimals: 6 }, [B]: { symbol: "tAST", decimals: 18 } },
  );
  assert.deepEqual(c.holdings.map((h) => [h.role, h.address.toLowerCase(), h.symbol, h.labelled]), [
    ["payout", A, "uUSD", true],
    ["customer", B, "tAST", true],
    ["known", K, null, false],
  ]);
});

test("a manifest without known tokens serves the two payment assets as holdings and nothing invented", () => {
  const A = "0x000000000000000000000000000000000000000a";
  const c = runtimeConfig({ contracts: { payoutToken: { address: A } } }, null, "http://127.0.0.1:8545", {});
  assert.deepEqual(c.holdings.map((h) => [h.role, h.symbol]), [["payout", null]]);
  assert.deepEqual(runtimeConfig({}, null, "http://127.0.0.1:8545").holdings, []);
});

test("a record is served only for the chain its manifest names; the practice-chain record never appears under a public manifest", () => {
  const local = { chainId: 31337, contracts: {}, identity: {} };
  const robinhood = { chainId: 46630, contracts: {}, identity: {} };
  const practiceRecord = { chainId: 31337, order: { id: "x" } };
  assert.deepEqual(runtimeConfig(local, practiceRecord, "/local/rpc").record, practiceRecord);
  assert.equal(runtimeConfig(robinhood, practiceRecord, "/local/rpc").record, null);
  assert.deepEqual(runtimeConfig(robinhood, { chainId: 46630, order: { id: "y" } }, "/local/rpc").record, { chainId: 46630, order: { id: "y" } });
  assert.equal(runtimeConfig(robinhood, { order: { id: "no chain id" } }, "/local/rpc").record, null);
  assert.equal(runtimeConfig(robinhood, null, "/local/rpc").record, null);
});
