// apps/web/tests/serve-config.test.mjs: the shape GET /local/config.json answers with, executed
// from the exact function the companion runs, without binding a socket or needing a chain.
//
// The companion is script/anvil/companion.mjs — one module, run on this machine by
// script/anvil/serve.sh and behind a public host by api/local.mjs. The pure functions are sliced
// out of it between two marker comments and evaluated here rather than imported, so this file
// cannot accidentally pull in the module's imports or its chain reads. If the markers move or a
// function is renamed, this fails loudly rather than testing a copy that drifted.

import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, dirname } from "node:path";
import { test } from "node:test";

import {
  LOCAL_MANIFEST,
  LOCAL_MANIFEST_WITHOUT_DIRECT_SETTLER,
  LOCAL_TOKEN_LABELS,
  TAST,
  UUSD,
} from "./fixtures/local-manifest.fixture.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..", "..");
const source = readFileSync(join(ROOT, "script", "anvil", "companion.mjs"), "utf8");

const begin = source.indexOf("// @runtimeConfig-begin");
const end = source.indexOf("// @runtimeConfig-end");
assert.ok(begin > 0 && end > begin, "companion.mjs carries the @runtimeConfig markers");
const slice = source.slice(begin, end);
const runtimeConfig = new Function(`${slice}\nreturn runtimeConfig;`)();

// THE MANIFEST THESE ROWS OWN. Hand written, committed, and unaffected by whether anyone has run
// the demo on this machine. `deployments/31337.local.json` is gitignored and regenerated by every
// `make business-demo` and `make anvil-test`, so a row that asserted a fixed value out of it was
// asserting against state that legitimately moves; see the fixture's own note.
const fullManifest = LOCAL_MANIFEST;

// The runtime manifest, when this machine happens to have one. Read separately, asserted
// separately, and never required: its absence is a normal state on a fresh clone.
const RUNTIME_MANIFEST_PATH = join(ROOT, "deployments", "31337.local.json");
const runtimeManifest = existsSync(RUNTIME_MANIFEST_PATH)
  ? JSON.parse(readFileSync(RUNTIME_MANIFEST_PATH, "utf8"))
  : null;

test("the served config still carries rpc, chainId, manifest and record", () => {
  const c = runtimeConfig({ chainId: 31337, contracts: {}, identity: {} }, { order: { id: "x" } }, "REDACTED");
  assert.equal(c.rpc, "REDACTED");
  assert.equal(c.chainId, 31337);
  assert.deepEqual(c.record, { order: { id: "x" } });
  assert.equal(c.manifest.chainId, 31337);
});
test("a manifest without an onboarding contract exposes null for every join field, never a guess", () => {
  const c = runtimeConfig({ chainId: 31337, contracts: { identityFixture: { address: "0x1" }, identityToken: { address: "0x2" } }, identity: { terminalStatusKey: "com.unica.terminal-status" } }, null, "REDACTED");
  assert.equal(c.merchantOnboarding, null);
  assert.equal(c.parentNode, null);
  assert.equal(c.parentName, null);
  assert.equal(c.identity, "0x1");
  assert.equal(c.identityToken, "0x2");
  assert.equal(c.terminalStatusKey, "com.unica.terminal-status");
});
test("a manifest with an onboarding contract exposes all five join fields", () => {
  const c = runtimeConfig({
    chainId: 31337,
    contracts: { merchantOnboarding: { address: "0xaaa" }, identityFixture: { address: "0xbbb" }, identityToken: { address: "0xccc" } },
    identity: { parentNode: "0x" + "1".repeat(64), parentName: "unica.eth", terminalStatusKey: "com.unica.terminal-status" }, // parentNode bytes32 vector
  }, null, "REDACTED");
  assert.equal(c.merchantOnboarding, "0xaaa");
  assert.equal(c.identity, "0xbbb");
  assert.equal(c.identityToken, "0xccc");
  assert.equal(c.parentNode, "0x" + "1".repeat(64)); // bytes32 vector
  assert.equal(c.parentName, "unica.eth");
});
test("a full manifest is served without a crash and says what it lacks", () => {
  const c = runtimeConfig(fullManifest, null, "REDACTED");
  assert.equal(c.chainId, 31337);
  assert.equal(c.identity, fullManifest.contracts.identityFixture.address);
  assert.equal(c.identityToken, fullManifest.contracts.identityToken.address);
  // A manifest may or may not carry merchantOnboarding. Either answer is fine; an exception is not.
  assert.ok(c.merchantOnboarding === null || /^0x[0-9a-fA-F]{40}$/.test(c.merchantOnboarding));
});
test("an empty manifest yields nulls, not a crash", () => {
  const c = runtimeConfig(undefined, null, "REDACTED");
  assert.equal(c.chainId, null);
  assert.equal(c.merchantOnboarding, null);
});

// ---- the business screens' half of the configuration ------------------------------------------

// The two local test assets and their read-off-chain labels come from the fixture, so these rows
// and the full-manifest rows below are talking about the same two tokens.
const LABELS = LOCAL_TOKEN_LABELS;
const withAssets = {
  chainId: 31337,
  environment: "LOCAL_ANVIL_NO_VALUE",
  contracts: { payoutToken: { address: UUSD }, assetToken: { address: TAST }, executor: { address: "0xexec" } },
  market: { marketId: "0xmarket", poolKey: { currency0: UUSD, currency1: TAST }, poolId: "0xpool", status: 4 },
  identity: {},
};

test("the assets are served with the role, symbol and decimal count each screen needs", () => {
  const c = runtimeConfig(withAssets, null, "REDACTED", LABELS);
  assert.deepEqual(c.assets.map((a) => [a.role, a.symbol, a.decimals, a.labelled]), [
    ["payout", "uUSD", 6, true],
    ["customer", "tAST", 18, true],
  ]);
  assert.equal(c.assets[0].address, UUSD);
});
test("an asset whose label could not be read is served unlabelled, never guessed", () => {
  const c = runtimeConfig(withAssets, null, "REDACTED", {});
  assert.deepEqual(c.assets.map((a) => [a.symbol, a.decimals, a.labelled]), [
    [null, null, false],
    [null, null, false],
  ]);
});
test("the market pair is active only at status 4", () => {
  assert.equal(runtimeConfig(withAssets, null, "REDACTED", LABELS).marketPair.active, true);
  const paused = { ...withAssets, market: { ...withAssets.market, status: 5 } };
  assert.equal(runtimeConfig(paused, null, "REDACTED", LABELS).marketPair.active, false);
  const seeded = { ...withAssets, market: { ...withAssets.market, status: 3 } };
  assert.equal(runtimeConfig(seeded, null, "REDACTED", LABELS).marketPair.active, false);
});
test("a manifest with no market serves no pair at all, rather than an empty one that looks usable", () => {
  const c = runtimeConfig({ chainId: 31337, contracts: {}, identity: {} }, null, "REDACTED", {});
  assert.equal(c.marketPair, null);
});
test("the direct settler is null until the deployment carries one", () => {
  assert.equal(runtimeConfig(withAssets, null, "REDACTED", LABELS).contracts.directSettlement, null);
  const withDirect = { ...withAssets, contracts: { ...withAssets.contracts, directSettlement: { address: "0xdirect" } } };
  assert.equal(runtimeConfig(withDirect, null, "REDACTED", LABELS).contracts.directSettlement, "0xdirect");
});
test("the product catalogue is null until the deployment carries one, and served verbatim once it does", () => {
  assert.equal(runtimeConfig(withAssets, null, "REDACTED", LABELS).contracts.productCatalog, null);
  const withCatalog = { ...withAssets, contracts: { ...withAssets.contracts, productCatalog: { address: "0xcatalog" } } };
  const c = runtimeConfig(withCatalog, null, "REDACTED", LABELS);
  assert.equal(c.contracts.productCatalog, "0xcatalog");
  // The control on the row: the two manifests differ in that one field and nothing else, so a
  // screen that finds no catalogue is being told the truth about the deployment, not guessing.
  assert.equal(c.contracts.executor, runtimeConfig(withAssets, null, "REDACTED", LABELS).contracts.executor);
});
test("the environment the manifest declares is served verbatim, for the label rule to judge", () => {
  assert.equal(runtimeConfig(withAssets, null, "REDACTED", LABELS).environment, "LOCAL_ANVIL_NO_VALUE");
  assert.equal(runtimeConfig({ chainId: 1, contracts: {}, identity: {} }, null, "REDACTED", {}).environment, null);
});
test("a full manifest serves both of its assets, its market pair and its direct settler", () => {
  const c = runtimeConfig(fullManifest, null, "REDACTED", LOCAL_TOKEN_LABELS);
  assert.equal(c.assets.length, 2);
  assert.deepEqual(
    c.assets.map((a) => [a.role, a.address, a.symbol]),
    [
      ["payout", UUSD, "uUSD"],
      ["customer", TAST, "tAST"],
    ],
  );
  assert.equal(c.marketPair.marketId, fullManifest.market.marketId);
  assert.equal(c.marketPair.active, true); // the fixture records status 4, ACTIVE
  assert.equal(c.contracts.executor, fullManifest.contracts.executor.address);
  assert.equal(c.contracts.directSettlement, fullManifest.contracts.directSettlement.address);
});
test("the same deployment before the direct settler existed serves null, not a guess", () => {
  const c = runtimeConfig(LOCAL_MANIFEST_WITHOUT_DIRECT_SETTLER, null, "REDACTED", LOCAL_TOKEN_LABELS);
  assert.equal(c.contracts.directSettlement, null);
  // The control on the row above: everything else about the two manifests is identical, so the
  // difference in that one field is the settler and nothing else.
  assert.equal(c.contracts.executor, fullManifest.contracts.executor.address);
  assert.equal(c.marketPair.marketId, fullManifest.market.marketId);
});
test("the runtime manifest on this machine, if there is one, is served verbatim", () => {
  if (!runtimeManifest) {
    // A stated negative, not a silent skip: no local deployment on this machine, nothing to serve.
    console.log("      (no deployments/31337.local.json on this machine — nothing to serve, nothing asserted)");
    return;
  }
  const c = runtimeConfig(runtimeManifest, null, "REDACTED");
  assert.equal(c.chainId, runtimeManifest.chainId);
  assert.equal(c.environment, runtimeManifest.environment ?? null);
  // Whatever the deployment carries is what is served. Asserting a FIXED answer here is what made
  // the earlier version of this row fail the moment the installation started deploying a settler.
  assert.equal(c.contracts.directSettlement, runtimeManifest.contracts?.directSettlement?.address ?? null);
  assert.equal(c.contracts.executor, runtimeManifest.contracts?.executor?.address ?? null);
  assert.equal(c.marketPair?.marketId ?? null, runtimeManifest.market?.marketId ?? null);
});

test("holdings are the two payment assets plus every known token, each listed once, labelled only when read", () => {
  const A = "0x000000000000000000000000000000000000000a";
  const B = "0x000000000000000000000000000000000000000b";
  const K = "0x000000000000000000000000000000000000000c";
  const c = runtimeConfig(
    { contracts: { payoutToken: { address: A }, assetToken: { address: B } }, knownTokens: [{ address: K }, { address: A.toUpperCase().replace("0X", "0x") }] },
    null,
    "http://127.0.0.1:8545",
    { [A]: { symbol: "uUSD", decimals: 6 }, [B]: { symbol: "tAST", decimals: 18 } },
  );
  assert.deepEqual(c.holdings.map((h) => [h.role, h.address.toLowerCase(), h.symbol, h.labelled]), [
    ["payout", A, "uUSD", true],
    ["customer", B, "tAST", true],
    ["known", K, null, false],
  ]);
});

test("a manifest without known tokens serves the two payment assets as holdings and nothing invented", () => {
  const A = "0x000000000000000000000000000000000000000a";
  const c = runtimeConfig({ contracts: { payoutToken: { address: A } } }, null, "http://127.0.0.1:8545", {});
  assert.deepEqual(c.holdings.map((h) => [h.role, h.symbol]), [["payout", null]]);
  assert.deepEqual(runtimeConfig({}, null, "http://127.0.0.1:8545").holdings, []);
});

test("a record is served only for the chain its manifest names; the practice-chain record never appears under a public manifest", () => {
  const local = { chainId: 31337, contracts: {}, identity: {} };
  const robinhood = { chainId: 46630, contracts: {}, identity: {} };
  const practiceRecord = { chainId: 31337, order: { id: "x" } };
  assert.deepEqual(runtimeConfig(local, practiceRecord, "/local/rpc").record, practiceRecord);
  assert.equal(runtimeConfig(robinhood, practiceRecord, "/local/rpc").record, null);
  assert.deepEqual(runtimeConfig(robinhood, { chainId: 46630, order: { id: "y" } }, "/local/rpc").record, { chainId: 46630, order: { id: "y" } });
  assert.equal(runtimeConfig(robinhood, { order: { id: "no chain id" } }, "/local/rpc").record, null);
  assert.equal(runtimeConfig(robinhood, null, "/local/rpc").record, null);
});

// ---- GET /local/catalog: the pure half ------------------------------------------------------------
//
// Sliced out of the SAME heredoc, between its own two markers, so these rows run the functions the
// server runs rather than a copy of them.
//
// EVERY RETURN VECTOR BELOW WAS PRODUCED BY `cast abi-encode` 1.3.5 from the struct declared in
// src/unica-v5/IProductCatalog.sol. That matters twice over. It is an INDEPENDENT encoder, so
// these rows compare this repository's decoder with somebody else's encoder rather than with
// itself; and it is reproducible, where a transcription of bytes a node once answered is not —
// the first draft of this file carried a hand-copied capture with one wrong word in it, and the
// decoder was blamed for the typist. The Haircut vector was then checked byte for byte against
// what the practice chain's own catalogue actually answered to `products(1)`, so the shape here
// is the shape the contract really returns.

const catalogBegin = source.indexOf("// @catalog-begin");
const catalogEnd = source.indexOf("// @catalog-end");
assert.ok(catalogBegin > 0 && catalogEnd > catalogBegin, "companion.mjs carries the @catalog markers");
const catalog = new Function(
  `${source.slice(catalogBegin, catalogEnd)}\nreturn { catalogQuery, decodeUintArray, decodeProduct, catalogIsUnknown, catalogProduct };`,
)();

const SELLER_ADDRESS = "0x70997970c51812dc3a010c7d01b50e0d17dc79c8";
const PAYOUT_ADDRESS = "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc";
const PRICED_IN = "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0";
const NOBODY_ADDRESS = "0x0000000000000000000000000000000000000000";

// products(1) on the practice chain: a one-off called Haircut, 25000000 base units.
const HAIRCUT_RETURN_VECTOR =
  "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c80000000000000000000000003c44cdddb6a900fa2b585dd299e03d12fa4293bc0000000000000000000000009fe46736679d2d9a65f0992f2272de9f3c7fa6e000000000000000000000000000000000000000000000000000000000017d784000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000074861697263757400000000000000000000000000000000000000000000000000"; // cast abi-encode vector
// products(2): a recurring one whose name needs two tail words, covering 2592000 seconds.
const MEMBERSHIP_RETURN_VECTOR =
  "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c80000000000000000000000003c44cdddb6a900fa2b585dd299e03d12fa4293bc0000000000000000000000009fe46736679d2d9a65f0992f2272de9f3c7fa6e000000000000000000000000000000000000000000000000000000000002625a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000278d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000124d6f6e74686c79206d656d626572736869700000000000000000000000000000"; // cast abi-encode vector
// productsOf for a seller with nothing listed: an offset word and a length of zero, and no more.
const EMPTY_LIST_RETURN_VECTOR =
  "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000"; // cast abi-encode vector
// cast abi-encode "f(uint256[])" "[1,2,7]" — an independent vector for the non-empty case.
const THREE_IDS_RETURN_VECTOR =
  "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000007"; // cast abi-encode vector

test("the endpoint answers one seller or one product, and refuses anything else by name", () => {
  assert.deepEqual(catalog.catalogQuery({ seller: SELLER_ADDRESS }), { kind: "seller", seller: SELLER_ADDRESS });
  assert.deepEqual(catalog.catalogQuery({ product: "4" }), { kind: "product", productId: "4" });
  assert.deepEqual(catalog.catalogQuery({ product: "007" }), { kind: "product", productId: "7" });
  const refused = [{}, { seller: "0x1" }, { seller: "not-an-address" }, { product: "0" }, { product: "-1" }, { product: "1.5" }, { product: "" }, { seller: SELLER_ADDRESS, product: "1" }];
  for (const asked of refused) {
    const answer = catalog.catalogQuery(asked);
    assert.equal(answer.kind, "bad", `${JSON.stringify(asked)} should have been refused`);
    assert.ok(answer.error.length > 10, "a refusal says what was wrong");
  }
  assert.equal(refused.length, 8); // a stated count: eight refusals asserted, none skipped
});

test("control: the refusal rule is one a real query can pass", () => {
  assert.equal(catalog.catalogQuery({ seller: SELLER_ADDRESS.toUpperCase().replace("0X", "0x") }).kind, "seller");
  assert.equal(catalog.catalogQuery({ product: "18446744073709551615" }).kind, "product");
});

test("a product decodes to exactly what the chain holds, name and all", () => {
  assert.deepEqual(catalog.decodeProduct(HAIRCUT_RETURN_VECTOR), {
    seller: SELLER_ADDRESS,
    payout: PAYOUT_ADDRESS,
    asset: PRICED_IN,
    price: "25000000",
    kind: "one-off",
    period: 0,
    onlyBuyer: NOBODY_ADDRESS,
    active: true,
    sold: false,
    name: "Haircut",
  });
});

test("a name longer than one word decodes whole, and a period is read as itself", () => {
  const p = catalog.decodeProduct(MEMBERSHIP_RETURN_VECTOR);
  assert.equal(p.name, "Monthly membership"); // eighteen bytes: two tail words, not one
  assert.equal(p.kind, "recurring");
  assert.equal(p.period, 2592000);
  assert.equal(p.price, "2500000");
});

test("control: the decoder does not simply agree with whatever it is given", () => {
  assert.notEqual(catalog.decodeProduct(HAIRCUT_RETURN_VECTOR).name, catalog.decodeProduct(MEMBERSHIP_RETURN_VECTOR).name);
  assert.equal(catalog.decodeProduct("0x"), null);
  assert.equal(catalog.decodeProduct(null), null);
});

test("a product nobody listed is recognised as unknown, never served as a real one", () => {
  // cast abi-encode of the same struct with every field at its default: what `products()` answers
  // for an id nobody has listed, since `_products` is a mapping and reading a gap never refuses.
  const ZERO_STRUCT_RETURN_VECTOR =
    "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000"; // cast abi-encode vector
  assert.equal(catalog.catalogIsUnknown(catalog.decodeProduct(ZERO_STRUCT_RETURN_VECTOR)), true);
  assert.equal(catalog.decodeProduct(ZERO_STRUCT_RETURN_VECTOR).name, ""); // a gap has no name, and does not throw
  assert.equal(catalog.catalogIsUnknown(catalog.decodeProduct(HAIRCUT_RETURN_VECTOR)), false);
  assert.equal(catalog.catalogIsUnknown(null), true);
});

test("a seller's list of numbers decodes, empty and not", () => {
  assert.deepEqual(catalog.decodeUintArray(EMPTY_LIST_RETURN_VECTOR), []);
  assert.deepEqual(catalog.decodeUintArray(THREE_IDS_RETURN_VECTOR), ["1", "2", "7"]);
  assert.deepEqual(catalog.decodeUintArray("0x"), []);
});

test("the served product carries the asset's own label, and never invents one", () => {
  const decoded = catalog.decodeProduct(HAIRCUT_RETURN_VECTOR);
  assert.deepEqual(catalog.catalogProduct("1", decoded, { symbol: "uUSD", decimals: 6 }), {
    id: "1",
    name: "Haircut",
    asset: PRICED_IN,
    symbol: "uUSD",
    decimals: 6,
    price: "25000000",
    kind: "one-off",
    period: 0,
    payout: PAYOUT_ADDRESS,
    onlyBuyer: null,
    active: true,
    sold: false,
    seller: SELLER_ADDRESS,
  });
  const unlabelled = catalog.catalogProduct("1", decoded, {});
  assert.equal(unlabelled.symbol, null);
  // never a guessed 18, which on a six-decimal asset is wrong by a factor of a million
  assert.equal(unlabelled.decimals, null);
});

test("no named buyer is served as null, not as an address of twenty zero bytes", () => {
  const anyone = catalog.catalogProduct("1", catalog.decodeProduct(HAIRCUT_RETURN_VECTOR), {});
  assert.equal(anyone.onlyBuyer, null);
  // control: a real named buyer survives
  const reserved = catalog.catalogProduct("1", { ...catalog.decodeProduct(HAIRCUT_RETURN_VECTOR), onlyBuyer: PAYOUT_ADDRESS }, {});
  assert.equal(reserved.onlyBuyer, PAYOUT_ADDRESS);
});
